---
- name: Настройка параметров ядра Linux
  hosts: for_task
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Установка максимального количества открытых файлов
      sysctl:
        name: fs.file-max
        value: 65535
        state: present
        reload: yes

    - name: Установка максимального количества PID
      sysctl:
        name: kernel.pid_max
        value: 65536
        state: present
        reload: yes

    - name: Установка диапазона IP-портов
      sysctl:
        name: net.ipv4.ip_local_port_range
        value: "2000 65000"
        state: present
        reload: yes

    - name: Применение исправления RFC 1337 (блокировка инъекции TCP RST пакетов)
      sysctl:
        name: net.ipv4.tcp_rfc1337
        value: 1
        state: present
        reload: yes
